[server]
headless = true
runOnSave = true
enableCORS = false
port = 8501
enableXsrfProtection = false
maxUploadSize = 200

[theme]
primaryColor = "#007bff"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = true

[logger]
level = "info"

[browser]
gatherUsageStats = false
